### ISSUE TITLE
Adding more than 5 IMUs to the I2C mux

### ISSUE THREAD

**Issue by BhavyaKrishna** [imsenthur/Arboc#1]
Considering our project need 7 IMU's to be connected, there are two things you can try
(i) Change the address of 2 MPU's to 0x69 and connect them to the any of the working channels, say SD0-SC0 and SD1-SC1 and read from those channels by using address 0x69.
(ii) Check if the problem is in the 6th channels of the I2C MUX by using the 7th and 8th channels with the first 5 channels transmitting data 

All this is suggested because you said you are currently not able to read 6 IMU's at the same time

**Comment by manuaatitya** [comment]
![relative_angle_6imus](https://user-images.githubusercontent.com/32318187/44305960-76534c00-a3a2-11e8-8dd2-402b048264b7.png)

Thanks for the suggestions :+1: 
i) Changing the address of the imu worked 
ii) The problem was with the 5th port in the i2c multiplexer , when i connect the imu to the 6th or 7th ports and get 6 readings it works fine even without changing the address.

The issue is solved but if i print values individually using only 1 imu connected to the ports the 5th port gives correct readings so ultimately the main problem is solved but i cant figure out why it is happening so.

I even tried using pullup resistors to the clock line and data line of the multiplexer even though the imu breakout boards have one but still no improvement in the results.

Welcoming logical suggestions to this issue.
